export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';
export const REQUEST_NODE_BLOCKS_STATUS = 'REQUEST_NODE_BLOCKS_STATUS';
export const RECIEVE_NODE_BLOCKS_SUCCESS = 'REVIEVE_NODE_BLOCKS_SUCCESS';
export const RECIEVE_NODE_BLOCKS_FAILURE = 'REVIEVE_NODE_BLOCKS_FAILURE';